#!/usr/bin/env zsh

for f in .zsh .zshrc .screenrc .vimrc .vim .emacs.d
do
  [ ~/$f -ef $(pwd)/$f ] || {
    echo symlinking $f
    [ -e ~/$f ] && mv ~/$f ~/$f.$(date +%Y%m%d%H%M%S)
    ln -s $(pwd)/$f ~/$f
  }
done
