#!/bin/bash

# need to prompt name and email for global git
# take in some params for git global config
# echo "Enter your username (Git)"
# read user

# echo "Enter your email (Git)"
# read email

# symlink dotfiles
# for f in .zsh .zshrc .screenrc .vimrc .vim .emacs.d .aliases .export_vars .gitconfig .gitignore
# for f in .zsh .zshrc .screenrc .vimrc .vim .emacs.d
for f in .screenrc .vimrc .vim .emacs.d .aliases .bashrc .gitconfig .gitignore
do
  [ ~/$f -ef $(pwd)/$f ] || {
    echo symlinking $f
    [ -e ~/$f ] && mv ~/$f ~/$f.$(date +%Y%m%d%H%M%S)
    ln -s $(pwd)/$f ~/$f
  }
done

# git config --global user.name "$user"
# git config --global user.email $email
git config --global core.editor vim

# assuming we are using bash or some other shell
test $SHELL = 'bash' && source ~/.bashrc && echo sourcing bashrc
test $SHELL = 'zsh' && source ~/.zshrc && echo sourcing zshrc
